title: "RealHomePrice"
output: html_document
date: "2022-11-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("caTools")
#install.packages('neuralnet')
#install.packages('sigmoid')
```


```{r loading packages}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(neuralnet)
library(sigmoid)
library(broom)
library(caTools)
library(devtools)
library(usethis)
```

## R Markdown


```{r} 
load("C:/RealHomePrice/data/cleaned_realtordata.rdata")
```

```{r selecting required columns}
#realtor_data1 <- realtor_data %>%
  #select(c('price','bed','bath','house_size'))
#realtor_data1

#In our original run, we did this to clean up the realtor data
```

```{r  removing rows with null values}
#cleaned_realtordata <- na.omit(realtor_data1)
## manually filtering the ouliers
filtered_realtor_data  <- cleaned_realtordata |> filter(price < 1000000 && bed < 15 && bath < 9 && house_size < 10000 )
## removing the price outliers 
outliers=boxplot(filtered_realtor_data$price,plot=FALSE)$out
outliers_data=filtered_realtor_data[which(filtered_realtor_data$price %in% outliers),]
filtered_realtor_data1= filtered_realtor_data[-which(filtered_realtor_data$price %in% outliers),]

```

```{r Normalization and Splitting data}
normalize2 <- function(x, na.rm = TRUE) {
    return((x- min(x)) / max(x))
}
normalized_data2 = as.data.frame(lapply(cleaned_realtordata, normalize2))

normalized_data3 <- normalized_data2[1:100000, ]

##Splitting Data
set.seed(12)
sample <- sample.split(normalized_data3$price, SplitRatio = 0.8) ## Splitting train and test data, train data = 80% of data 


train_data <- subset(normalized_data3, sample == TRUE)
test_data <- subset(normalized_data3, sample == FALSE)
```




```{r Getting Linear model setup}
linear_model_fit <- lm(price~bed+bath+house_size, data =train_data )
#quick summary of our model
summary(linear_model_fit)
#using tidy() to create a tibble of coefficients to use for neural network weights later
#weights_table <- tidy(linear_model_fit)
#user_data = data.frame(bed, bath, acre_lot, house_size)
```


```{r normalize function}
#   Function to Normalize user input  using (- min/max)
normalize_input <- function(user_Data) {
  bed = (user_Data[1,1]-min(cleaned_realtordata$bed))/(max(cleaned_realtordata$bed))
  bath = (user_Data[1,2]-min(cleaned_realtordata$bath))/(max(cleaned_realtordata$bath))
  house_size = (user_Data[1,3]-min(cleaned_realtordata$house_size))/(max(cleaned_realtordata$house_size))
  nor_User_data <- data.frame(bed, bath, house_size)
  return(nor_User_data)
}
```


```{r Using a function}
##Function that takes in dataframe of normalized user data and gives out the output
predict_lm <- function(nor_User_data, linear_model_fit1 = linear_model_fit) {
  if (class(linear_model_fit) != "lm"
  ) stop("This function needs an LM model")
  predict(linear_model_fit, nor_User_data)
}
```

```{r}
#Function to unscale the price
unscale_price <- function(price) {
  price*(max(cleaned_realtordata$price))+min(cleaned_realtordata$price)
}
```

```{r}
pricelm <- predict_lm(nor_User_data)
pricelm
#unscaling linear model price prediction
unscaled_price <- unscale_price(pricelm)
```




```{r}

#neuralmodel3 <- neuralnet(price~bed+bath+house_size,data=train_data,hidden=2, threshold=0.01,act.fct=relu, rep=1, linear.output=TRUE)

#This is how we saved the Neural model, this function takes a long time to load, so we put the data in a file in the data folder for ease of access for the user.
            
```

```{r}

#save(neuralmodel, file ="./neuralmodel3.RDa")
#Saving the neural net that was created in the previous block
```



```{r}
load("C:/RealHomePrice/data/neuralmodel3.Rda")
```


```{r}
#plotting
plot(neuralmodel)

```

```{r Block to create the predict_nn function}
#Creating the function to load in the neural net against the user data
predict_nn <- function(nor_User_data) {
  predict(neuralmodel, nor_User_data)
}
```


```{r}
predict_Price <- function(user_data) {
  nor_User_data <- normalize_input(user_data)
  lm_price <- predict_lm(nor_User_data)
  nn_price <- predict_nn(nor_User_data)
  lm_pricefinal <- unscale_price(lm_price)
  nn_pricefinal <- unscale_price(nn_price)
  
  prices <- data.frame(nn_pricefinal, lm_pricefinal)
  return(prices)
 
}
```

```{r FinalCode}
{
    bed = as.numeric(readline("Enter bed : "));
    bath = as.numeric(readline("Enter bath : "));
    house_size = as.numeric(readline("Enter house_size: "));
    user_data = data.frame(bed, bath, house_size)
}

```



```{r}

predict_Price(user_data)

```

